[package]
name = "init-net-test"
version = "0.1.0"
authors = ["Oliver Gould <ver@buoyant.io>"]
edition = "2018"
publish = false

[dependencies]
bytes = "0.6"
futures = "0.3"
http = "0.2"
structopt = "0.3"
tokio = { version = "0.3", features = ["io-util", "macros", "net", "rt-multi-thread", "stream", "time"] }
tracing = "0.1"
tracing-subscriber = "0.2"
