[package]
name = "init-net-test"
version = "0.1.0"
authors = ["Oliver Gould <ver@buoyant.io>"]
edition = "2018"
publish = false

[dependencies]
bytes = "0.5"
futures = "0.3"
tokio = { version = "0.2", features = ["io-util", "macros", "rt-threaded", "stream"] }
trust-dns-resolver = "0.19.5"
