---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: init-net-test
  name: init-net-test-server
spec:
  selector:
    app: init-net-test
    role: server
  ports:
    - port: 4444
      targetPort: 4444

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: init-net-test
    role: client
  name: init-net-test-client
spec:
  selector:
    matchLabels:
      app: init-net-test
      role: client
  template:
    metadata:
      labels:
        app: init-net-test
        role: client
    spec:
      containers:
        - name: main
          image: olix0r/init-net-test:v1
          args: ["client", "init-net-test-server", "4444"]
      initContainers:
        - name: iptables-init
          image: gcr.io/linkerd-io/proxy-init:edge-19.3.2
          args:
            - --incoming-proxy-port
            - "4143"
            - --outgoing-proxy-port
            - "4140"
            - --proxy-uid
            - "2102"
            - --inbound-ports-to-ignore
            - 4190,4191
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
            privileged: false
            runAsNonRoot: false
            runAsUser: 0

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: init-net-test
    role: server
  name: init-net-test-server
spec:
  selector:
    matchLabels:
      app: init-net-test
      role: server
  template:
    metadata:
      labels:
        app: init-net-test
        role: server
    spec:
      containers:
        - name: main
          image: olix0r/init-net-test:v1
          args: ["server", "4444"]
          ports:
            - containerPort: 4444
              protocol: TCP
      initContainers:
        - name: iptables-init
          image: gcr.io/linkerd-io/proxy-init:edge-19.3.2
          args:
            - --incoming-proxy-port
            - "4143"
            - --outgoing-proxy-port
            - "4140"
            - --proxy-uid
            - "2102"
            - --inbound-ports-to-ignore
            - 4190,4191
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
            privileged: false
            runAsNonRoot: false
            runAsUser: 0
