---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: init-net-test
  name: init-net-test-server
spec:
  selector:
    app: init-net-test
    role: server
  ports:
    - port: 4444
      targetPort: 4444

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: init-net-test
    role: client
  name: init-net-test-client
spec:
  selector:
    matchLabels:
      app: init-net-test
      role: client
  template:
    metadata:
      labels:
        app: init-net-test
        role: client
    spec:
      containers:
        - name: main
          image: olix0r/init-net-test:v5
          args: ["client", "init-net-test-server", "4444"]

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: init-net-test
    role: server
  name: init-net-test-server
spec:
  selector:
    matchLabels:
      app: init-net-test
      role: server
  template:
    metadata:
      labels:
        app: init-net-test
        role: server
    spec:
      containers:
        - name: main
          image: olix0r/init-net-test:v5
          args: ["server", "4444"]
          ports:
            - containerPort: 4444
              protocol: TCP
              name: echo
