---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: init-net-test
    role: client
  name: init-net-test-client
spec:
  selector:
    matchLabels:
      app: init-net-test
      role: client
  template:
    metadata:
      labels:
        app: init-net-test
        role: client
    spec:
      containers:
        - name: main
          image: ghcr.io/olix0r/init-net-test:v7
          args: ["client", "init-net-test-server:4444"]
