apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: init-net-test
    role: client
  name: init-net-test-client
  namespace: {{.Release.Namespace}}
spec:
  selector:
    matchLabels:
      app: init-net-test
      role: client
  replicas: {{int .Values.client.replicas}}
  template:
    metadata:
      labels:
        app: init-net-test
        role: client
      annotations:
        linkerd.io/inject: {{.Values.client.linkerdInject | default false | ternary "enabled" "disabled" }}
{{- if .Values.linkerd.proxyImage}}
        config.linkerd.io/proxy-image: {{.Values.linkerd.proxyImage}}
{{- end}}
{{- if .Values.linkerd.proxyVersion}}
        config.linkerd.io/proxy-version: {{.Values.linkerd.proxyVersion}}
{{- end}}
    spec:
      containers:
        - name: main
          image: ghcr.io/olix0r/init-net-test:v7
          args:
            - client
{{- range $i, $e := until (.Values.server.services | int) }}
            - "tcp://echo-{{$i}}:4444"
{{- end}}

