{{- $ns := .Release.Namespace}}
{{- $replicas := int .Values.server.replicas}}
{{- $linkerd := .Values.linkerd}}
{{- $inject := .Values.server.linkerdInject}}
{{- range $i, $e := until (.Values.server.services | int) }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: init-net-test
  name: echo-{{$i}}
  namespace: {{$ns}}
spec:
  selector:
    app: init-net-test
    role: server
    instance: {{quote $i}}
  ports:
    - port: 4444
      targetPort: 4444

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: init-net-test
    role: server
    instance: {{quote $i}}
  name: server-{{$i}}
  namespace: {{$ns}}
spec:
  selector:
    matchLabels:
      app: init-net-test
      role: server
      instance: {{quote $i}}
  replicas: {{$replicas}}
  template:
    metadata:
      labels:
        app: init-net-test
        role: server
        instance: {{quote $i}}
      annotation:
        linkerd.io/inject: {{$inject | default false | ternary "enabled" "disabled" }}
{{- if $linkerd.proxyImage}}
        config.linkerd.io/proxy-image: {{$linkerd.proxyImage}}
{{- end}}
{{- if $linkerd.proxyVersion}}
        config.linkerd.io/proxy-version: {{$linkerd.proxyVersion}}
{{- end}}
    spec:
      containers:
        - name: main
          image: ghcr.io/olix0r/init-net-test:v7
          args: ["server", "4444"]
          ports:
            - containerPort: 4444
              protocol: TCP
              name: echo
{{- end -}}
