{{- $ns := .Release.Namespace }}
{{- $image := .Values.image }}
{{- $replicas := int .Values.server.replicas }}
{{- $linkerd := .Values.linkerd }}
{{- $inject := .Values.server.linkerdInject }}
{{- $opaque := .Values.server.opaque }}
{{- $reverse := .Values.reverse }}
{{- $hostIP := .Values.hostIP }}
{{- range $i, $e := until (int .Values.server.services) }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tcp-echo
  name: echo-{{ printf "%03d" $i }}
  namespace: {{ $ns }}
spec:
  selector:
    app: tcp-echo
    role: server
    instance: {{quote $i}}
  ports:
    - port: 4445
      targetPort: 4445
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tcp-echo
    role: server
    instance: {{ quote $i }}
  name: server-{{ printf "%03d" $i }}
  namespace: {{ $ns }}
spec:
  selector:
    matchLabels:
      app: tcp-echo
      role: server
      instance: {{quote $i}}
  replicas: {{ $replicas }}
  template:
    metadata:
      labels:
        app: tcp-echo
        role: server
        instance: {{ quote $i }}
      annotations:
        linkerd.io/inject: {{ $inject | default false | ternary "enabled" "disabled" }}
        {{- if $linkerd.proxyImage }}
        config.linkerd.io/proxy-image: {{ $linkerd.proxyImage }}
        {{- end }}
        {{- if $linkerd.proxyVersion }}
        config.linkerd.io/proxy-version: {{ $linkerd.proxyVersion }}
        {{- end }}
        {{- if or $reverse $opaque }}
        config.linkerd.io/opaque-ports: "4445"
        {{- end }}
    spec:
      containers:
        - name: main
          image: {{ $image }}
          env:
            - name: RUST_LOG
              value: debug
          args:
            - server
            - "4445"
            - --reverse={{ $reverse }}
          ports:
            - containerPort: 4445
              hostPort: 4445
              hostIP: {{ $hostIP }}
              protocol: TCP
              name: echo
{{- end }}
